CREATE TABLE notification
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message varchar(255) NOT NULL,
    source  varchar(255) NOT NULL
);

CREATE SEQUENCE notification_id_sequence START WITH 1 INCREMENT BY 1;
